version: '3'
services:
  zookeeper:
    image: zookeeper:3.5.5
    ports:
      - "2183:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
      - ZOO_MAX_CLIENT_CNXNS=2000
  admin:
    image: apache/dubbo-admin
    ports:
      - "18080:8080"
    environment:
      - admin.registry.address=zookeeper://172.19.10.14:2181,172.19.10.14:2182,172.19.10.16:2183
      - admin.config-center=zookeeper://172.19.10.14:2181,172.19.10.14:2182,172.19.10.16:2183
      - admin.metadata-report.address=zookeeper://172.19.10.14:2181,172.19.10.14:2182,172.19.10.16:2183
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_MESSAGE_MAX_BYTES=10000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_DELETE_RETENTION_MS=1000
#      - KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      - JMX_PORT=1099
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_PORT: 27020
      ME_CONFIG_MONGODB_SERVER: 172.19.10.14
    depends_on:
      - mongo
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      KM_ARGS: -Djava.net.preferIPv4Stack=true